[package]
name = "flatpak_jetbrain_updater"
version = "0.0.1"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.15", features = ["default"]}
tokio = { version = "1.44.2", features = ["full"] }
serde_json = "1.0.140"
serde_yaml = "0.9.33"
regex = "1.11.1"
quick-xml = "0.37.4"
